apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page-deployment
  labels:
    app: landing-page
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/landing-page-config-map.yaml") . | sha256sum }}
    spec:
      containers:
        - name: landing-page-container
          image: {{ tpl (index .Values "theia-cloud" "landingPage" "image" | toString) . }}
          imagePullPolicy: {{ if (index .Values "theia-cloud" "landingPage" "imagePullPolicy") }}{{ tpl (index .Values "theia-cloud" "landingPage" "imagePullPolicy" | toString) . }}{{ else }}{{ tpl (index .Values "theia-cloud" "imagePullPolicy" | toString) . }}{{ end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /config.js
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: landing-page-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js

          # --- CORRECTED BLOCK ---
          # We use 'index' because "theia-cloud" has a dash
          {{- if (index .Values "theia-cloud" "landingPage" "logoData") }}
          - name: landing-page-config
            mountPath: /usr/share/nginx/html/logo.png
            subPath: logo.png
          {{- end }}
          # -----------------------

      {{- if (index .Values "theia-cloud" "landingPage" "imagePullSecret") }}
      imagePullSecrets:
        - name: {{ tpl (index .Values "theia-cloud" "landingPage" "imagePullSecret" | toString) . }}
      {{- end }}
      volumes:
        - name: landing-page-config
          configMap:
            name: landing-page-config