# Ceph CSI Helm chart values file

# Configuration for RBD (Block Storage)
csiConfig:
 - clusterID: "ce707c35-2ff3-48b1-b122-aa9ef23d12d1" 
   monitors:
     - "mon1.ceph.rbg.tum.de"
     - "mon2.ceph.rbg.tum.de"
     - "mon3.ceph.rbg.tum.de"
     - "mon4.ceph.rbg.tum.de"
     - "mon5.ceph.rbg.tum.de"

# Create Storage Classes
storageClass:
  create: true
  name: "csi-rbd-sc"
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"

  clusterID: "ce707c35-2ff3-48b1-b122-aa9ef23d12d1" 
  pool: "ASE-rbd-kubernetes"
  dataPool: "ASE-rbddata-ssd-kubernetes"

secret: 
  create: true

  userID: "ASE.rbd.kubernetes"
  userKey: #FIXME