apps:
  - name: java-17-latest
    image: ghcr.io/ls1intum/theia/java-17:pr-50
    requestsMemory: 2000M
    requestsCpu: 500m
    limitsMemory: 2400M

  - name: c-latest
    image: ghcr.io/ls1intum/theia/c:latest
    requestsMemory: 100M
    requestsCpu: 200m
    limitsMemory: 2400M

  - name: javascript-latest
    image: ghcr.io/ls1intum/theia/javascript:latest
    requestsMemory: 100M
    requestsCpu: 200m
    limitsMemory: 2400M

  - name: ocaml-latest
    image: ghcr.io/ls1intum/theia/ocaml:latest
    requestsMemory: 100M
    requestsCpu: 200m
    limitsMemory: 2400M

  - name: python-latest
    image: ghcr.io/ls1intum/theia/python:latest
    requestsMemory: 100M
    requestsCpu: 200m
    limitsMemory: 2400M

  - name: rust-latest
    image: ghcr.io/ls1intum/theia/rust:latest
    requestsMemory: 100M
    requestsCpu: 200m
    limitsMemory: 2400M
