apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: instance-cert
spec:
  secretName: ws-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "{{ .Values.hosts.configuration.instance }}.{{ .Values.hosts.configuration.baseHost }}"
  dnsNames:
    - "{{ .Values.hosts.configuration.instance }}.{{ .Values.hosts.configuration.baseHost }}"
  privateKey:
    rotationPolicy: Never
