apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: landing-page-cert
spec:
  secretName: landing-page-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "{{ .Values.hosts.configuration.landing }}.{{ .Values.hosts.configuration.baseHost }}"
  dnsNames:
    - "{{ .Values.hosts.configuration.landing }}.{{ .Values.hosts.configuration.baseHost }}"
  privateKey:
    rotationPolicy: Never