apiVersion: v2
name: tum-theia-cloud
description: A Helm chart for managing TUM Theia Cloud
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: theia-cloud
    version: 1.1.0-next.1
    repository: "https://eclipse-theia.github.io/theia-cloud-helm"

  - name: theia-certificates
    version: 0.1.0
    repository: "file://../theia-certificates"

  - name: theia-appdefinitions
    version: 0.1.0
    repository: "file://../theia-appdefinitions"

  - name: theia-shared-cache
    version: 0.1.4
    repository: "https://ls1intum.github.io/theia-shared-cache/"
