hosts:
  configuration:
    baseHost: artemis.cit.tum.de
    service: service.theia
    landing: theia
    instance: instance.theia

wildcardCertificate: # The base64 encoded wildcard certificate
wildcardKey: # The base64 encoded wildcard key
